server:
  port: 9002
spring:
  application:
    name: consumer-feign-hystri
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
logging:
  level:
    root: INFO